# Generated by Django 3.1.2 on 2021-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('petrolium_product', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
