# Generated by Django 3.1.2 on 2021-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(),
        ),
    ]
