# Generated by Django 3.1.2 on 2021-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210506_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
